version: "3.8"

services:
  metabase:
    build: .
    container_name: metabase_test
    ports:
      - "3000:3000"
    environment:
      MB_QUERY_ROW_LIMIT: 10000
    volumes:
      - "./my_cleaned_data_for_metabase.db:/metabase_data/my_cleaned_data_for_metabase.db"
