global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules and send alerts to Alertmanager
rule_files:
  - "alerts.yml"
  # - "second_rules.yml"

# Scrape configurations
scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Scrape Node Exporter for system metrics
  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'

  # Scrape Job Scraper Web Application
  - job_name: 'job-scraper-web'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['job-scraper-web:5000']
        labels:
          service: 'job-scraper'

  # Scrape PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'

  # Scrape Redis Exporter
  - job_name: 'redis-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  # Scrape Cadvisor for container metrics
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor' 