version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: job_db
    environment:
      POSTGRES_USER: jobuser
      POSTGRES_DB: jobsdb
      POSTGRES_PASSWORD: jobuser_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-migrations
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: job_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:
