# Job Scraper Application Configuration

# Application settings
application:
  name: "Job Scraper"
  version: "2.0.0"
  debug: false
  upload_folder: "uploads"
  data_dir: "data"
  backup_dir: "data/backups"
  cors:
    enabled: true
    origins:
      - "http://localhost:5000"
      - "http://127.0.0.1:5000"
    methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "PATCH"
    allow_credentials: true

# Scraper settings
scraper:
  max_pages: 5
  rate_limit_ms: 1000
  max_concurrent_requests: 5
  timeout_seconds: 30
  retry:
    max_retries: 3
    min_retry_delay_ms: 500
    max_retry_delay_ms: 5000
    backoff_factor: 2
  sources:
    - name: "example_source"
      enabled: true
      url_template: "https://example.com/jobs?page={page}"
      max_pages: 3
      selectors:
        job_list: ".job-list"
        job_item: ".job-item"
        title: ".job-title"
        company: ".company-name"
        location: ".job-location"
        description: ".job-description"
        url: ".job-link"
        salary: ".job-salary"
        posted_date: ".job-date"
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"

# Database settings
database:
  schema: "jobdata"
  pool_size: 20
  max_overflow: 10
  timeout_seconds: 30
  retry_attempts: 3
  echo: false

# API settings
api:
  rate_limit:
    enabled: true
    limit: 100
    period_seconds: 60
  pagination:
    default_limit: 50
    max_limit: 1000
  versions:
    - "v1"
  endpoints:
    - name: "jobs"
      enabled: true
      methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "PATCH"
    - name: "search"
      enabled: true
      methods:
        - "GET"
        - "POST"
    - name: "stats"
      enabled: true
      methods:
        - "GET"

# Logging settings
logging:
  level: "INFO"
  json_format: false
  log_to_file: true
  log_to_console: true
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file:
    max_bytes: 10485760  # 10 MB
    backup_count: 5
    log_dir: "logs"
  request_logging: true 